"""add extracted_text and failure_reason

Revision ID: b77c33e64044
Revises: 634814c78f19
Create Date: 2026-07-30 18:26:07.968589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77c33e64044'
down_revision: Union[str, Sequence[str], None] = '634814c78f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'failure_reason')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
